apiVersion: batch/v1
kind: CronJob
metadata:
  name: myapp-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: myapp-container
            image: myapp-image:latest
            command: ["/bin/sh"]
            args: ["-c", "echo Hello from the CronJob"]
          restartPolicy: OnFailure